using CryptoExchange.Net.Objects;
using Lighter.Net.Objects.Internal;
using Lighter.Net.Objects.Models;
using System;
using System.Text.Json.Serialization;

namespace Lighter.Net.Converters
{
    [JsonSerializable(typeof(LighterOrders))]
    [JsonSerializable(typeof(LighterStatus))]
    [JsonSerializable(typeof(LighterSystemConfig))]
    [JsonSerializable(typeof(LighterSymbols))]
    [JsonSerializable(typeof(LighterL1Info))]
    [JsonSerializable(typeof(LighterAssets))]
    [JsonSerializable(typeof(LighterOrderBook))]
    [JsonSerializable(typeof(LighterTrades))]
    [JsonSerializable(typeof(LighterSymbolDetails))]
    [JsonSerializable(typeof(LighterExchangeStats))]
    [JsonSerializable(typeof(LighterAccount))]
    [JsonSerializable(typeof(LighterNonce))]
    [JsonSerializable(typeof(LighterAccounts))]
    [JsonSerializable(typeof(LighterAccountLimits))]
    [JsonSerializable(typeof(LighterAccountMetadata))]
    [JsonSerializable(typeof(LighterPnl))]
    [JsonSerializable(typeof(LighterResponse))]
    [JsonSerializable(typeof(LighterLiquidations))]
    [JsonSerializable(typeof(LighterFundingHistory))]
    [JsonSerializable(typeof(LighterTransactionResult))]
    [JsonSerializable(typeof(LighterTransactionsResult))]
    [JsonSerializable(typeof(LighterUserTrades))]
    [JsonSerializable(typeof(LighterDepositHistory))]
    [JsonSerializable(typeof(LighterTransferHistory))]
    [JsonSerializable(typeof(LighterWithdrawalHistory))]
    [JsonSerializable(typeof(LighterAnnouncements))]
    [JsonSerializable(typeof(LighterApiKeys))]
    [JsonSerializable(typeof(LighterKlines))]
    [JsonSerializable(typeof(LighterMarkKlines))]
    [JsonSerializable(typeof(LighterFundingRateHistory))]
    [JsonSerializable(typeof(LighterCurrentFundingRates))]

    [JsonSerializable(typeof(LighterRequestWrapper<LighterTxRequest>))]
    [JsonSerializable(typeof(LighterRequestWrapper<LighterBatchTxRequest>))]
    [JsonSerializable(typeof(LighterSocketTransactionResult))]
    [JsonSerializable(typeof(LighterSocketPong))]
    [JsonSerializable(typeof(LighterSocketRequest))]
    [JsonSerializable(typeof(LighterSocketUpdate))]
    [JsonSerializable(typeof(LighterSocketError))]
    [JsonSerializable(typeof(LighterTradeUpdate))]
    [JsonSerializable(typeof(LighterOrderBookUpdate))]
    [JsonSerializable(typeof(LighterBookTickerUpdate))]
    [JsonSerializable(typeof(LighterTickerUpdate))]
    [JsonSerializable(typeof(LighterAllTickerUpdate))]
    [JsonSerializable(typeof(LighterSpotTickerUpdate))]
    [JsonSerializable(typeof(LighterAllSpotTickerUpdate))]
    [JsonSerializable(typeof(LighterKlineUpdate))]
    [JsonSerializable(typeof(LighterMarkPriceKlineUpdate))]
    [JsonSerializable(typeof(LighterAccountUpdate))]
    [JsonSerializable(typeof(LighterUserStatsUpdate))]
    [JsonSerializable(typeof(LighterOrderUpdate))]
    [JsonSerializable(typeof(LighterUserTradeUpdate))]
    [JsonSerializable(typeof(LighterPositionUpdate))]
    [JsonSerializable(typeof(LighterBalancesUpdate))]

    [JsonSerializable(typeof(string))]
    [JsonSerializable(typeof(int?))]
    [JsonSerializable(typeof(int))]
    [JsonSerializable(typeof(long?))]
    [JsonSerializable(typeof(long))]
    [JsonSerializable(typeof(decimal))]
    [JsonSerializable(typeof(decimal?))]
    [JsonSerializable(typeof(short))]
    [JsonSerializable(typeof(DateTime))]
    [JsonSerializable(typeof(DateTime?))]
    [JsonSerializable(typeof(Parameters))]
    [JsonSerializable(typeof(string[]))]
    [JsonSerializable(typeof(int[]))]
    internal partial class LighterSourceGenerationContext : JsonSerializerContext
    {
    }
}
